name: Build and Push Docker Image on Release

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read # For actions/checkout to fetch code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Image with Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Dockerfile
          image: kowalski-binary
          tags: ${{ github.sha }}

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry:  ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Image details
        if: steps.build-push.outputs.digest
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
