name: Build and Push Docker Image on Release

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read # For actions/checkout to fetch code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image with Buildah
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Dockerfile
          image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: ${{ github.sha }}
          push: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image details
        if: steps.build-push.outputs.digest
        run: |
          echo "Digest: ${{ steps.build-push.outputs.digest }}"
          echo "Tags: ${{ steps.build-push.outputs.tags }}"
