name: Build and Push Docker Image on Release

on:
  push:
    branches:
      - release

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read # For actions/checkout to fetch code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          registry: ghcr.io
          image_name: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: ${{ github.sha }}
          labels: |
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}/commit/${{ github.sha }}

      - name: Image details
        if: steps.build-push.outputs.digest
        run: |
          echo "Digest: ${{ steps.build-push.outputs.digest }}"
          echo "Tags: ${{ steps.build-push.outputs.tags }}"
